<?php

namespace Modules\PublicPage\Database\Factories;

use Modules\PublicPage\Models\Event;
use Illuminate\Database\Eloquent\Factories\Factory;

class EventFactory extends Factory
{
    protected $model = Event::class;

    public function definition(): array
    {
        return [
            'name' => fake()->sentence(3),
            'description' => fake()->paragraph(),
            'icon' => fake()->randomElement(['calendar', 'video', 'music', 'conference']),
            'category' => fake()->randomElement(['conference', 'workshop', 'seminar', 'meetup']),
            'event_date' => fake()->dateTimeBetween('-1 year', '+1 year'),
            'slug' => NULL, // Will be generated by model
            'is_published' => fake()->boolean(70), // 70% chance of being published
        ];
    }

    public function published(): static
    {
        return $this->state(fn (array $attributes) => [
            'is_published' => TRUE,
        ]);
    }

    public function draft(): static
    {
        return $this->state(fn (array $attributes) => [
            'is_published' => FALSE,
        ]);
    }
}
